"""Remove rating column from reviews

Revision ID: 00416c4ecebb
Revises: 
Create Date: 2025-05-29 00:45:27.082251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00416c4ecebb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
